openapi: 3.1.0
info:
  title: Infrastructure API
  description: Enables comprehensive monitoring and management of critical colonial infrastructure systems, including life support, power generation, and emergency response.
  version: 1.0.0
  contact:
    name: Weyland-Yutani Support
    url: https://weyland-yutani.com/support
    email: support@weyland-yutani.com
  termsOfService: https://weyland-yutani.com/terms
servers:
  - url: https://api.weyland-yutani.com/infrastructure
    description: Production server
  - url: https://staging.api.weyland-yutani.com/infrastructure
    description: Staging server
paths:
  /colonies/{colonyId}/systems:
    get:
      summary: Retrieve infrastructure system status
      description: Provides real-time status and telemetry data for critical infrastructure systems in a specified colony.
      parameters:
        - name: colonyId
          in: path
          required: true
          description: The unique identifier for the colony.
          schema:
            type: string
        - name: systemType
          in: query
          required: false
          description: Filter results by a specific system type (e.g., life support, power generation).
          schema:
            type: string
            enum: [life-support, power-generation, waste-management, communication]
      responses:
        '200':
          description: Infrastructure system status retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  colonyId:
                    type: string
                    description: The unique identifier for the colony.
                  systems:
                    type: array
                    items:
                      type: object
                      properties:
                        systemType:
                          type: string
                          description: The type of system (e.g., life support, power generation).
                        status:
                          type: string
                          description: Current status of the system (e.g., operational, degraded, offline).
                        telemetry:
                          type: object
                          description: Key metrics for the system.
                          additionalProperties:
                            type: number
        '404':
          description: Colony not found.
        '400':
          description: Invalid colony ID.
  /colonies/{colonyId}/alerts:
    get:
      summary: Retrieve active alerts
      description: Provides a list of active alerts for a specified colony's infrastructure systems, including severity levels and recommended actions.
      parameters:
        - name: colonyId
          in: path
          required: true
          description: The unique identifier for the colony.
          schema:
            type: string
      responses:
        '200':
          description: Active alerts retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  colonyId:
                    type: string
                    description: The unique identifier for the colony.
                  alerts:
                    type: array
                    items:
                      type: object
                      properties:
                        alertId:
                          type: string
                          description: Unique identifier for the alert.
                        systemType:
                          type: string
                          description: The type of system the alert is associated with.
                        severity:
                          type: string
                          enum: [low, medium, high, critical]
                          description: The severity level of the alert.
                        message:
                          type: string
                          description: Description of the alert.
                        recommendedAction:
                          type: string
                          description: Recommended action to resolve the alert.
        '404':
          description: Colony not found.
  /colonies/{colonyId}/maintenance:
    post:
      summary: Schedule maintenance for a system
      description: Schedules maintenance for a specific system in the colony's infrastructure.
      parameters:
        - name: colonyId
          in: path
          required: true
          description: The unique identifier for the colony.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                systemType:
                  type: string
                  description: The type of system to schedule maintenance for (e.g., life support, power generation).
                scheduledDate:
                  type: string
                  format: date-time
                  description: The proposed date and time for maintenance.
                maintenanceDetails:
                  type: string
                  description: Additional details about the maintenance request.
              required:
                - systemType
                - scheduledDate
      responses:
        '201':
          description: Maintenance scheduled successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  colonyId:
                    type: string
                    description: The unique identifier for the colony.
                  maintenanceId:
                    type: string
                    description: Unique identifier for the maintenance request.
                  scheduledDate:
                    type: string
                    format: date-time
                    description: The scheduled date and time for maintenance.
        '400':
          description: Invalid request data.
        '404':
          description: Colony not found.
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message.
        code:
          type: integer
          description: HTTP status code.
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
security:
  - ApiKeyAuth: []
tags:
  - name: Infrastructure
    description: Endpoints for monitoring and managing colonial infrastructure systems.

