openapi: 3.1.0
info:
  title: Navigation API
  description: Provides access to Weyland-Yutani's deep space navigation platform, offering real-time hazard alerts, route optimization, and integration with automated piloting systems.
  version: 1.0.0
  contact:
    name: Weyland-Yutani Support
    url: https://weyland-yutani.com/support
    email: support@weyland-yutani.com
  termsOfService: https://weyland-yutani.com/terms
servers:
  - url: https://api.weyland-yutani.com/navigation
    description: Production server
  - url: https://staging.api.weyland-yutani.com/navigation
    description: Staging server
paths:
  /routes:
    post:
      summary: Calculate optimal route
      description: Provides an optimized route between two points in space, considering hazards, fuel efficiency, and travel time.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                origin:
                  type: object
                  description: Starting location for the route.
                  properties:
                    system:
                      type: string
                      description: Name of the star system.
                    coordinates:
                      type: object
                      properties:
                        x:
                          type: number
                        y:
                          type: number
                destination:
                  type: object
                  description: Destination location for the route.
                  properties:
                    system:
                      type: string
                      description: Name of the star system.
                    coordinates:
                      type: object
                      properties:
                        x:
                          type: number
                        y:
                          type: number
                fuelCapacity:
                  type: number
                  description: Available fuel capacity in kilograms.
              required:
                - origin
                - destination
      responses:
        '200':
          description: Route calculated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  routeId:
                    type: string
                    description: Unique identifier for the calculated route.
                  waypoints:
                    type: array
                    items:
                      type: object
                      properties:
                        system:
                          type: string
                          description: Name of the star system.
                        coordinates:
                          type: object
                          properties:
                            x:
                              type: number
                            y:
                              type: number
                        hazards:
                          type: array
                          items:
                            type: string
                          description: List of hazards along the waypoint.
                  estimatedTime:
                    type: string
                    format: duration
                    description: Estimated travel time for the route.
                  fuelConsumption:
                    type: number
                    description: Estimated fuel consumption for the route in kilograms.
        '400':
          description: Invalid request data.
        '404':
          description: Route calculation failed due to missing data.
  /hazards:
    get:
      summary: Retrieve active hazards
      description: Returns a list of active hazards in a specified star system.
      parameters:
        - name: system
          in: query
          required: true
          description: Name of the star system.
          schema:
            type: string
      responses:
        '200':
          description: Active hazards retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  system:
                    type: string
                    description: Name of the star system.
                  hazards:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          description: Type of hazard (e.g., radiation zone, micrometeorite field).
                        coordinates:
                          type: object
                          properties:
                            x:
                              type: number
                            y:
                              type: number
                        severity:
                          type: string
                          enum: [low, medium, high, critical]
                          description: Severity level of the hazard.
        '404':
          description: Star system not found.
        '400':
          description: Invalid request parameters.
  /routes/{routeId}/status:
    get:
      summary: Retrieve route status
      description: Provides the status and updates for a specific calculated route, including any deviations or alerts.
      parameters:
        - name: routeId
          in: path
          required: true
          description: Unique identifier for the route.
          schema:
            type: string
      responses:
        '200':
          description: Route status retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  routeId:
                    type: string
                    description: Unique identifier for the route.
                  currentStatus:
                    type: string
                    description: Current status of the route.
                  alerts:
                    type: array
                    items:
                      type: string
                    description: List of active alerts affecting the route.
        '404':
          description: Route not found.
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message.
        code:
          type: integer
          description: HTTP status code.
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
security:
  - ApiKeyAuth: []
tags:
  - name: Navigation
    description: Endpoints for calculating routes, retrieving hazards, and monitoring route statuses.

